name: Keep Alive

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

concurrency:
  group: keep-alive
  cancel-in-progress: false

jobs:
  ping:
    name: Ping health endpoint
    runs-on: ubuntu-latest
    steps:
      - name: Curl health endpoint with retries
        shell: bash
        run: |
          set -euo pipefail
          URL="https://sideby.me/_health"
          echo "Pinging $URL"
          for attempt in {1..3}; do
            HTTP_STATUS=$(curl -sS -o /dev/null -w "%{http_code}" --max-time 20 --connect-timeout 10 -H "User-Agent: keep-alive-bot/1.0" "$URL" || echo "000")
            echo "Attempt ${attempt}: HTTP ${HTTP_STATUS}"
            if [[ "$HTTP_STATUS" =~ ^2|3[0-9]{2}$ ]] || { [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 400 ]; }; then
              echo "Health check OK"
              exit 0
            fi
            sleep 5
          done
          echo "Health check failed after retries"
          exit 1
